workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    working_directory: .
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa